"""
Latitude MedTech — Skills & Knowledge Profiles
================================================
Generates a *living* skill/KB profile for every agent plus a master
firm-wide profile. Each file has two parts:

  1. A curated SKILL CATALOG (capabilities, KB ownership, sources, target)
     — the durable definition of what the agent can do.
  2. An AUTO-GENERATED accumulation block (between <!-- ACC --> markers)
     — all-time items/chunks/domains pulled live from the memory DB, so the
     "skill/KB accumulation" is always current, not hand-maintained.

Outputs:
    Athena/knowledge_base/skills/<agent>.md   (one per agent)
    LatitudeMedTech/SKILLS.md                 (master, firm root)

Usage:
    python skills_profile.py            # regenerate every profile + master
    python skills_profile.py --agent fda
    python skills_profile.py --print fda # print accumulation, write nothing
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime

from pathconfig import AGENTS_DIR, KB_DIR, FIRM_ROOT
sys.path.insert(0, str(AGENTS_DIR))

from memory import Memory

try:
    from learning_sources import AGENT_SOURCES
except Exception:
    AGENT_SOURCES = {}

SKILLS_DIR = KB_DIR / "skills"
MASTER_PATH = FIRM_ROOT / "SKILLS.md"

ACC_START = "<!-- ACC:START — auto-generated by skills_profile.py, do not edit by hand -->"
ACC_END   = "<!-- ACC:END -->"

# ── Curated skill catalog ─────────────────────────────────────────────────────
# One entry per agent. `skills` = durable capabilities; `kb_owns` = KB it writes
# and other agents query; `consumers` = who relies on it; `target` = weekly
# learning minimum (mirrors hr_agent thresholds).

CATALOG = {
    "consulting": {
        "label": "Management Consulting Agent", "tier": "Senior Manager", "target": 5,
        "mission": "Build and maintain the firm's consulting methodology library so every "
                   "deliverable lands at McKinsey/BCG quality.",
        "skills": [
            "Apply MECE, Pyramid Principle, McKinsey 7-S, BCG Matrix, Porter's 5 Forces, Issue Trees",
            "Architect deck structures: Executive Summary (SCQA), Strategy, Regulatory Strategy, M&A Diligence, Pitch",
            "Synthesise public Big 4 frameworks into reusable templates (no verbatim reproduction)",
            "Storyboard board-ready narratives and executive summaries",
        ],
        "kb_owns": ["knowledge_base/consulting/ (frameworks, methodologies, slide structures, case studies)"],
        "consumers": "All agents via kb_context('consulting framework') to elevate deliverable quality.",
    },
    "ma_intelligence": {
        "label": "M&A Intelligence Agent", "tier": "Senior Manager", "target": 5,
        "mission": "Maintain MedTech/Pharma deal intelligence and QARA impact analysis.",
        "skills": [
            "Pre-close diligence checklists and post-close integration playbooks (QARA lens)",
            "Pattern-match landmark deals (Medtronic/Covidien, Abbott/St. Jude, J&J/Synthes, Stryker/Wright, BD/Bard)",
            "Diagnose integration failure patterns and regulatory exposure",
            "50-year historical deal research via Brave queries",
        ],
        "kb_owns": ["knowledge_base/ma/ (deal intelligence, QARA frameworks, lessons learned)"],
        "consumers": "Consulting Agent, Regulatory Strategy, and Steven for diligence engagements.",
    },
    "fda": {
        "label": "FDA Agent", "tier": "Manager", "target": 4,
        "mission": "Track FDA pathways, guidance, enforcement, and recalls; ground regulatory outputs.",
        "skills": [
            "510(k), PMA, De Novo pathway selection and reasoning",
            "21 CFR Part 820 (QSR) and design-controls interpretation",
            "Warning-letter and recall trend analysis for enforcement risk",
            "CDRH guidance monitoring and summarisation",
        ],
        "kb_owns": ["knowledge_base/FDA/, FDA_Warning_Letters/, FDA_Recalls/"],
        "consumers": "Coaching, Content, Consulting, ISO Coach, and human review.",
    },
    "eu_mdr": {
        "label": "EU MDR Agent", "tier": "Manager", "target": 3,
        "mission": "Maintain EU MDR 2017/745 knowledge for CE-marking and conformity strategy.",
        "skills": [
            "EU MDR 2017/745 article and annex interpretation",
            "Notified Body conformity-assessment routes by device class",
            "EUDAMED, UDI, and PMS/PSUR obligations",
            "Cross-walk FDA vs MDR requirements for dual-market strategy",
        ],
        "kb_owns": ["knowledge_base/EU_MDR/"],
        "consumers": "Consulting Agent, Regulatory Strategy, Content.",
    },
    "iso": {
        "label": "ISO Coach Agent", "tier": "Manager", "target": 3,
        "mission": "Generate ISO 13485 clause coaching one clause at a time, QMS-grounded.",
        "skills": [
            "ISO 13485:2016 clause-by-clause coaching (no verbatim standard text in RAG)",
            "QMS design: CAPA, document control, management review, risk per ISO 14971",
            "Map ISO 13485 clauses to 21 CFR Part 820 equivalents",
            "Six Sigma / Lean quality-system improvement",
        ],
        "kb_owns": ["coaching/iso13485/ (generated clause coaching)"],
        "consumers": "Coaching clients, Consulting Agent, Content.",
    },
    "coaching": {
        "label": "Coaching Brief Agent", "tier": "Manager", "target": 3,
        "mission": "Produce MedTech career coaching briefs through the human-gated orchestrator graph.",
        "skills": [
            "Career-strategy briefs for RA/QA/MedTech professionals",
            "Leadership and talent-development framing (HBR/McKinsey People)",
            "Intake → brief → human-gate → finalize workflow (LangGraph)",
            "Disclaimer + label discipline on every client-facing brief",
        ],
        "kb_owns": ["coaching/briefs/ (generated briefs)"],
        "consumers": "Steven (human gate), client coaching line.",
    },
    "content": {
        "label": "Content Agent", "tier": "Manager", "target": 3,
        "mission": "Write MedTech Meridian articles at McKinsey/BCG register with specific citations.",
        "skills": [
            "Long-form article drafting (900–1,200 words) across a 10-category curriculum",
            "Banned-phrase enforcement and specific-citation discipline (21 CFR §, ISO clause, $ figures)",
            "House-style structure: H1 title, H2 sections, frontmatter stripped at render",
            "Topic rotation and dedup against published history",
        ],
        "kb_owns": ["content/drafts/, content/published/"],
        "consumers": "Marketing, Substack publication, Steven (human gate).",
    },
    "briefing": {
        "label": "Briefing Agent", "tier": "Senior Associate", "target": 5,
        "mission": "Produce the daily/periodic regulatory + industry intelligence briefing.",
        "skills": [
            "Synthesise FDA, IMDRF, biotech, and SoCal-MedTech feeds into a concise briefing",
            "Prioritise signal over noise across many sources",
            "Surface SoCal corridor and competitor intelligence",
            "Cite every item with source attribution",
        ],
        "kb_owns": ["briefings/ (generated briefings)"],
        "consumers": "Steven, all agents as daily situational context.",
    },
    "rag": {
        "label": "RAG Ingestion Agent", "tier": "Senior Associate", "target": 2,
        "mission": "Ingest, chunk, and index documents into the central KB for retrieval.",
        "skills": [
            "Document chunking, tagging by category/agent, and dedup by URL hash",
            "TF-IDF retrieval grounding for KB-first prompting",
            "Maintain knowledge_base/index.json integrity",
            "Deep-scrape orchestration for regulatory corpora",
        ],
        "kb_owns": ["knowledge_base/ (root RAG docs + index.json)"],
        "consumers": "Every agent via KBQuery.search() / central_kb_context().",
    },
    "hr": {
        "label": "HR / L&D Manager Agent", "tier": "Business Function", "target": 0,
        "mission": "Track health, learning velocity, and accumulation of every agent; flag and recommend.",
        "skills": [
            "Per-agent GREEN/YELLOW/RED scoring on learning velocity and error rate",
            "CAPA flagging on 3+ events and remediation recommendations",
            "Scorecard reporting to ops/hr/ for Steven's review",
            "Workforce accumulation oversight (this profile system)",
        ],
        "kb_owns": ["ops/hr/ (scorecards, CAPA records)"],
        "consumers": "Steven; surfaced in dashboard and via voice.",
    },
    "voice_bridge": {
        "label": "Voice Assistant (Athena)", "tier": "Associate", "target": 1,
        "mission": "Real-time voice interface: STT → orchestrator → streaming TTS.",
        "skills": [
            "Wake-word detection (openWakeWord; custom 'Hi Athena' pending)",
            "Whisper STT with auto mic selection and confidence logging",
            "Streaming Kokoro TTS, sentence-split, ~1.2s first audio",
            "Route spoken queries to the agent orchestrator and speak results",
        ],
        "kb_owns": ["(no KB ownership — consumes the central KB)"],
        "consumers": "Steven (primary interface).",
    },
}

# Display order: by tier seniority then label
ORDER = ["consulting", "ma_intelligence", "fda", "eu_mdr", "iso", "coaching",
         "content", "briefing", "rag", "hr", "voice_bridge"]


def _sources_for(agent):
    src = AGENT_SOURCES.get(agent, [])
    return [f"{s['name']} ({s['domain']})" for s in src]


def _fmt_ts(ts):
    return ts[:16].replace("T", " ") if ts else "Never"


def _acc_block(agent, acc):
    """The auto-generated accumulation section (between ACC markers)."""
    domains = ", ".join(acc["domains"]) if acc["domains"] else "—"
    lines = [
        ACC_START,
        "## Skill & KB Accumulation (live)",
        f"_Last refreshed: {datetime.now().strftime('%Y-%m-%d %H:%M')}_",
        "",
        f"- **Total knowledge items:** {acc['total_items']}  "
        f"({acc['learn_items']} curated learning + {acc['kb_docs']} RAG docs)",
        f"- **Total chunks indexed:** {acc['total_chunks']}  "
        f"({acc['learn_chunks']} learning + {acc['kb_chunks']} RAG)",
        f"- **Domains accumulated:** {domains}",
        f"- **Last accumulation activity:** {_fmt_ts(acc['last'])}",
        ACC_END,
    ]
    return "\n".join(lines)


def render_profile(agent, cat, acc):
    sources = _sources_for(agent)
    src_md = "\n".join(f"- {s}" for s in sources) if sources else "- (sources not yet instrumented)"
    skills_md = "\n".join(f"- {s}" for s in cat["skills"])
    owns_md = "\n".join(f"- {o}" for o in cat["kb_owns"])
    target = cat["target"]
    target_md = f"{target} new items/week" if target else "Not applicable (oversight role)"

    return f"""# {cat['label']} — Skills & Knowledge Profile

**Agent key:** `{agent}`  |  **Tier:** {cat['tier']}  |  **Weekly learning target:** {target_md}

## Mission
{cat['mission']}

## Skill Catalog
{skills_md}

## Knowledge Base Owned
{owns_md}

## Consumed By
{cat['consumers']}

## Learning Sources
{src_md}

{_acc_block(agent, acc)}

---
*Curated skills are durable; the accumulation block is regenerated from the memory DB by `skills_profile.py`. Alpha — Steve Review Required.*
"""


def render_master(rows):
    """rows = list of (agent, cat, acc)."""
    total_items = sum(a["total_items"] for _, _, a in rows)
    total_chunks = sum(a["total_chunks"] for _, _, a in rows)
    all_domains = sorted({d for _, _, a in rows for d in a["domains"]})

    lines = [
        "# Latitude MedTech — Master Skills & Knowledge Profile",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')} by `skills_profile.py`",
        "",
        "Firm-wide index of every agent's skill catalog and accumulated knowledge. "
        "Per-agent detail lives in `Athena/knowledge_base/skills/<agent>.md`.",
        "",
        "## Firm Totals",
        f"- **Agents profiled:** {len(rows)}",
        f"- **Total knowledge items accumulated:** {total_items}",
        f"- **Total chunks indexed:** {total_chunks}",
        f"- **Domains covered ({len(all_domains)}):** {', '.join(all_domains) if all_domains else '—'}",
        "",
        "## Accumulation by Agent",
        "",
        "| Agent | Tier | Items | Chunks | Last activity |",
        "|---|---|--:|--:|---|",
    ]
    for agent, cat, acc in rows:
        lines.append(
            f"| {cat['label']} (`{agent}`) | {cat['tier']} | "
            f"{acc['total_items']} | {acc['total_chunks']} | {_fmt_ts(acc['last'])} |"
        )

    lines += ["", "## Skill Coverage by Agent", ""]
    for agent, cat, acc in rows:
        lines.append(f"### {cat['label']} (`{agent}`)")
        lines.append(f"*{cat['mission']}*")
        for s in cat["skills"]:
            lines.append(f"- {s}")
        lines.append("")

    lines += [
        "---",
        "*Regenerate with `python skills_profile.py`. Alpha — Steve Review Required.*",
    ]
    return "\n".join(lines)


def generate(targets=None):
    SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    mem = Memory()
    targets = targets or ORDER
    rows = []
    for agent in targets:
        cat = CATALOG.get(agent)
        if not cat:
            print(f"  ! Unknown agent: {agent}")
            continue
        acc = mem.get_skill_accumulation(agent)
        rows.append((agent, cat, acc))
        out = SKILLS_DIR / f"{agent}.md"
        out.write_text(render_profile(agent, cat, acc), encoding="utf-8")
        print(f"  + {out.relative_to(FIRM_ROOT)}  "
              f"({acc['total_items']} items, {acc['total_chunks']} chunks)")

    # Master file always reflects the full roster in canonical order
    all_rows = [(a, CATALOG[a], mem.get_skill_accumulation(a)) for a in ORDER]
    MASTER_PATH.write_text(render_master(all_rows), encoding="utf-8")
    print(f"  + {MASTER_PATH.relative_to(FIRM_ROOT)}  (master)")
    mem.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--agent", type=str, default="", help="Single agent, or blank for all")
    parser.add_argument("--print", dest="print_only", type=str, default="",
                        help="Print one agent's accumulation, write nothing")
    args = parser.parse_args()

    if args.print_only:
        mem = Memory()
        acc = mem.get_skill_accumulation(args.print_only)
        print(f"\n{args.print_only} accumulation:")
        for k, v in acc.items():
            print(f"  {k:<14} {v}")
        mem.close()
        return

    print(f"\nLatitude MedTech — Skills Profile Generation "
          f"({datetime.now().strftime('%Y-%m-%d %H:%M')})")
    generate([args.agent] if args.agent else None)
    print("Done.")


if __name__ == "__main__":
    main()
