"""
Agent 5 — Substack Draft Publisher
=====================================
Sends a reviewed content draft to your Substack publication
via Substack's email-to-draft feature.

HOW IT WORKS:
Substack gives every publication a secret email address.
Anything you email to it becomes a draft in your dashboard.
This agent reads your approved draft files and emails them.

SETUP (one time):
1. Log into Substack
2. Go to Settings > Publishing > Email to draft
3. Copy your secret draft email address
4. Add it to your .env file as: SUBSTACK_DRAFT_EMAIL=your-secret@substack.com
5. Add your Gmail or SMTP credentials to .env (see below)

Usage:
    python substack_agent.py                    (interactive — pick a draft)
    python substack_agent.py --file "path.md"   (send specific file)
    python substack_agent.py --latest           (send most recent draft)

.env variables needed:
    SUBSTACK_DRAFT_EMAIL=your-secret-draft@substack.com
    SMTP_EMAIL=your-gmail@gmail.com
    SMTP_PASSWORD=your-app-password   (Gmail App Password, not regular password)
"""

import os
import sys
import re
import smtplib
import logging
import argparse
from pathlib import Path
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv(Path.home() / 'Athena' / 'voice' / '.env')

DRAFTS_DIR    = Path.home() / 'Athena' / 'content' / 'drafts'
PUBLISHED_DIR = Path.home() / 'Athena' / 'content' / 'published'
LOG_DIR       = Path.home() / 'Athena' / 'logs'
PUBLISHED_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / 'substack_agent.log'),
        logging.StreamHandler(sys.stdout),
    ]
)
log = logging.getLogger('substack_agent')

SUBSTACK_EMAIL = os.getenv('SUBSTACK_DRAFT_EMAIL', '')
SMTP_EMAIL     = os.getenv('SMTP_EMAIL', '')
SMTP_PASSWORD  = os.getenv('SMTP_PASSWORD', '')
SMTP_HOST      = os.getenv('SMTP_HOST', 'smtp.gmail.com')
SMTP_PORT      = int(os.getenv('SMTP_PORT', '587'))


# ── Draft parsing ─────────────────────────────────────────────────────────────

def parse_draft(file_path: Path) -> dict:
    content = file_path.read_text(encoding='utf-8')

    # Extract frontmatter
    title    = ""
    angle    = ""
    body     = content

    if content.startswith('---'):
        parts = content.split('---', 2)
        if len(parts) >= 3:
            frontmatter = parts[1]
            body        = parts[2].strip()
            for line in frontmatter.splitlines():
                if line.startswith('title:'):
                    title = line.replace('title:', '').strip()
                elif line.startswith('angle:'):
                    angle = line.replace('angle:', '').strip()

    # Strip the H1 if it duplicates the title
    body_lines = body.splitlines()
    if body_lines and body_lines[0].startswith('# '):
        body = '\n'.join(body_lines[1:]).strip()

    return {
        'title':    title or file_path.stem,
        'angle':    angle,
        'body':     body,
        'filename': file_path.name,
        'path':     file_path,
    }


def markdown_to_html(md: str) -> str:
    """Minimal markdown to HTML for email body."""
    lines   = md.splitlines()
    html    = []
    for line in lines:
        line = line.strip()
        if not line:
            html.append('<br>')
        elif line.startswith('## '):
            html.append(f'<h2>{line[3:]}</h2>')
        elif line.startswith('### '):
            html.append(f'<h3>{line[4:]}</h3>')
        elif line.startswith('# '):
            html.append(f'<h1>{line[2:]}</h1>')
        elif line.startswith('**') and line.endswith('**'):
            html.append(f'<strong>{line[2:-2]}</strong><br>')
        else:
            # Inline bold
            line = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', line)
            line = re.sub(r'\*(.+?)\*',     r'<em>\1</em>',         line)
            html.append(f'<p>{line}</p>')
    return '\n'.join(html)


# ── Email sending ─────────────────────────────────────────────────────────────

def send_to_substack(draft: dict, dry_run: bool = False) -> bool:
    if not SUBSTACK_EMAIL:
        log.error("SUBSTACK_DRAFT_EMAIL not set in .env")
        log.error("Get it from: Substack > Settings > Publishing > Email to draft")
        return False

    if not SMTP_EMAIL or not SMTP_PASSWORD:
        log.error("SMTP_EMAIL and SMTP_PASSWORD not set in .env")
        log.error("For Gmail: create an App Password at myaccount.google.com/apppasswords")
        return False

    subject  = draft['title']
    html_body = markdown_to_html(draft['body'])

    full_html = f"""<html><body>
{html_body}
<hr>
<p><em>Draft generated by Latitude MedTech Content Agent — {datetime.now().strftime('%B %d, %Y')}</em></p>
<p><em>Educational content only. Not regulatory advice.</em></p>
</body></html>"""

    if dry_run:
        print(f"\n[DRY RUN] Would send:")
        print(f"  To:      {SUBSTACK_EMAIL}")
        print(f"  From:    {SMTP_EMAIL}")
        print(f"  Subject: {subject}")
        print(f"  Length:  {len(draft['body'])} chars")
        return True

    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From']    = SMTP_EMAIL
        msg['To']      = SUBSTACK_EMAIL
        msg.attach(MIMEText(draft['body'], 'plain', 'utf-8'))
        msg.attach(MIMEText(full_html,     'html',  'utf-8'))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.sendmail(SMTP_EMAIL, SUBSTACK_EMAIL, msg.as_string())

        log.info(f"Sent to Substack drafts: {subject}")
        return True

    except smtplib.SMTPAuthenticationError:
        log.error("Gmail auth failed. Use an App Password, not your regular password.")
        log.error("Create one at: myaccount.google.com/apppasswords")
        return False
    except Exception as e:
        log.error(f"Send failed: {e}")
        return False


def mark_published(draft: dict):
    src = draft['path']
    dst = PUBLISHED_DIR / src.name
    src.rename(dst)
    log.info(f"Moved to published: {dst.name}")


# ── Draft selection ───────────────────────────────────────────────────────────

def list_drafts() -> list:
    drafts = sorted(DRAFTS_DIR.glob('*.md'), key=lambda f: f.stat().st_mtime, reverse=True)
    return drafts


def interactive_select() -> Path:
    drafts = list_drafts()
    if not drafts:
        print(f"\nNo drafts found in {DRAFTS_DIR}")
        print("Run content_agent.py first to generate a draft.")
        sys.exit(0)

    print("\nAvailable drafts:")
    print("=" * 50)
    for i, f in enumerate(drafts):
        mtime = datetime.fromtimestamp(f.stat().st_mtime).strftime('%Y-%m-%d')
        print(f"  {i+1}. [{mtime}] {f.stem[:60]}")
    print()

    choice = input("Select draft number to send (or 'q' to quit): ").strip()
    if choice.lower() == 'q':
        sys.exit(0)
    try:
        return drafts[int(choice) - 1]
    except (ValueError, IndexError):
        print("Invalid selection.")
        sys.exit(1)


# ── Setup check ───────────────────────────────────────────────────────────────

def check_setup():
    missing = []
    if not SUBSTACK_EMAIL:
        missing.append("SUBSTACK_DRAFT_EMAIL")
    if not SMTP_EMAIL:
        missing.append("SMTP_EMAIL")
    if not SMTP_PASSWORD:
        missing.append("SMTP_PASSWORD")

    if missing:
        print("\nSubstack Publisher — Setup Required")
        print("=" * 50)
        print("\nAdd these to your .env file:")
        print(f"  C:\\Users\\huann\\Athena\\voice\\.env\n")
        for var in missing:
            if var == "SUBSTACK_DRAFT_EMAIL":
                print(f"  {var}=your-secret@substack.com")
                print(f"    (Get from: Substack > Settings > Publishing > Email to draft)\n")
            elif var == "SMTP_EMAIL":
                print(f"  {var}=your-gmail@gmail.com\n")
            elif var == "SMTP_PASSWORD":
                print(f"  {var}=your-app-password")
                print(f"    (Create at: myaccount.google.com/apppasswords)")
                print(f"    (Use App Password, NOT your regular Gmail password)\n")
        return False
    return True


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("\nLatitude MedTech — Substack Draft Publisher")
    print("=" * 50)

    parser = argparse.ArgumentParser()
    parser.add_argument('--file',    help='Path to specific draft .md file')
    parser.add_argument('--latest',  action='store_true', help='Send most recent draft')
    parser.add_argument('--dry-run', action='store_true', help='Preview without sending')
    args = parser.parse_args()

    if not check_setup():
        sys.exit(1)

    # Select draft
    if args.file:
        file_path = Path(args.file)
        if not file_path.exists():
            log.error(f"File not found: {args.file}")
            sys.exit(1)
    elif args.latest:
        drafts = list_drafts()
        if not drafts:
            print("No drafts found. Run content_agent.py first.")
            sys.exit(0)
        file_path = drafts[0]
        log.info(f"Using most recent draft: {file_path.name}")
    else:
        file_path = interactive_select()

    draft = parse_draft(file_path)

    print(f"\nTitle:  {draft['title']}")
    print(f"File:   {draft['filename']}")
    print(f"Length: {len(draft['body'])} characters")

    if not args.dry_run:
        confirm = input("\nSend to Substack drafts? (y/n): ").strip().lower()
        if confirm != 'y':
            print("Cancelled.")
            sys.exit(0)

    success = send_to_substack(draft, dry_run=args.dry_run)

    if success and not args.dry_run:
        move = input("Move to published folder? (y/n): ").strip().lower()
        if move == 'y':
            mark_published(draft)

    if success:
        print("\nDone. Check your Substack dashboard for the draft.")
        print("https://substack.com/dashboard")


if __name__ == '__main__':
    main()
